### ISSUE TITLE
Use of ES6

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/Thomas-Project-Week-6#5]
You've used some great ES6+ features, such as array destructuring and template literals. Up your game on your iteration and use some array methods!

https://github.com/FACxBeamery/Thomas-Project-Week-6/blob/a02e1bc1daedb3727fc72f2aa6d02ff6890af021/src/utils/Status.js#L16

**Comment by TKostrzewski** [comment]
Thank you! Yes, I've gone with the .forEach() array method. Thank you for your suggestion😄👍🏻.

Issue resolved in commit: https://github.com/FACxBeamery/Thomas-Project-Week-6/commit/7519df71c9acb78975f113fd14bde4c0e6c00637
