### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/Thomas-Project-Week-6#6]
https://github.com/FACxBeamery/Thomas-Project-Week-6/blob/a02e1bc1daedb3727fc72f2aa6d02ff6890af021/src/utils/Status.js#L50-L77

You repeat more or less the same JSX three times. Could you accomplish this without repeating your code?

Also, there is no need to wrap text in quotes and curly braces in your JSX. You only need curly braces when you're including a Javascript expression such as a variable, function or conditional rendering.

`<p>{"Hello world"}</p> === <p>Hello world</p>`

**Comment by TKostrzewski** [comment]
Great suggestion, thank you! Yes, the suggestion has been implemented😄👍🏻
